services:
  app: #custom key name could have also been my-app
    # image: python:3.13.7-slim-trixie
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
      - 3000:8000
    command: 
      python -m http.server 8000
          